name:                aoc2017
version:             0.1.0.0
github:              valeksenko/aoc2017
license:             BSD3
author:              Val Aleksenko
maintainer:          v.aleksenko@gmail.com
copyright:           2017 Val Aleksenko

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/valeksenko/aoc2017#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aoc2017-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2017

tests:
  aoc2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2017
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
